FROM ghcr.io/theseus-dev/amd-compile-amd64-builder

RUN apt-get update && apt-get install -y cmake libgoogle-glog-dev libgflags-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev libceres-dev sudo libboost-all-dev

# ENV CERES_VERSION="2.2.0"
# RUN git clone https://ceres-solver.googlesource.com/ceres-solver && \
#     cd ceres-solver && \
#     git checkout tags/${CERES_VERSION} && \
#     mkdir build && cd build && \
#     cmake .. -DCMAKE_BUILD_TYPE=RelWithDebugInfo && \
#     make -j$(nproc) install && \
#     rm -rf ../../ceres-solver

RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" && \
dpkg -i /tmp/ros2-apt-source.deb && \
apt update && \
apt install -y ros-humble-desktop


# Accept build arguments for user creation
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG USERNAME=user

# Create user with specified UID/GID
RUN groupadd -g ${GROUP_ID} ${USERNAME} && \
    useradd -u ${USER_ID} -g ${GROUP_ID} -m -s /bin/bash ${USERNAME} && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers    

# Set working directory and ownership
WORKDIR /workspace
RUN chown -R ${USERNAME}:${USERNAME} /workspace